# Config database
DB:
  DB_HOST: db
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  DB_PORT: 5432

SERVER:
  SERVER_PORT: 3000
  SERVER_READ_TIMEOUT: 60
  SERVER_WRITE_TIMEOUT: 60

SECRET_KEY: LgszAIV5dBwmy93buOvFDSvmXaam1rzjNAHQ9HJNizE
